ELLIMS/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('eldashboard.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eldashboard/forms.py
from django import forms
from ELLIMS import settings

from .models import *

class SampleForm(forms.ModelForm):

   #setup the datepicker input and display date formates
   received = forms.DateField(
      widget=forms.DateInput(format=settings.DATE_INPUT_FORMATS[0]),
      input_formats=(settings.DATE_INPUT_FORMATS[0],)
   )

   client = forms.ModelChoiceField(queryset=Clients.objects.order_by('name'))

   class Meta:
      model = Sample
      fields = ['name', 'clientref', 'batch', 'condition', 'description', 'storage', 'received', 'client', 'notificationgroup']
      labels = {
         'clientref': 'Client Ref',
         'notificationgroup': 'Notification Group'
      }


class ClientForm(forms.ModelForm):

   class Meta:
      model = Clients
      fields = '__all__'

class TestMethodForm(forms.ModelForm):

   CHOICES = (
      (0, 'N/A'),
      (1, 'Relative Error'),
      (2, 'Absolute Error')
   )

   errortype = forms.ChoiceField(choices=CHOICES, label="Error Type")

   class Meta:
      model = TestMethods
      fields = '__all__'
      labels = {
         'decimalplaces': 'Decimal Places',
         'tmnumber': 'TM #',
         'reporttype': 'Report Type'
      }



class ContactForm(forms.ModelForm):

   class Meta:
      model = Contacts
      fields = ['firstname', 'lastname', 'email', 'phone', 'client']
      widgets = {'client': forms.HiddenInput()}


class JobForm(forms.ModelForm):

   class Meta:
      model = Job
      fields = ['client', 'notificationgroup', 'ponumber']
      labels = {
         'ponumber': "PO Number",
         'notificationgroup': 'Notification Group'
      }




class ReportTemplateForm(forms.ModelForm):

   class Meta:
      model = ReportTemplates
      fields = ['name', 'report_type', 'document']

templates/forms/clientform.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <input id="renderstring" type="hidden" value="{{ renderstring }}">
    <div class="card page-card">
      <div class="card-body">
        <h5 class="card-title">
            <a class="btn btn-info" href="{% url 'listclients' %}">Back</a>
            {% if id %}
                Client #{{ id }}
                <a class="btn btn-danger float-md-right" href="{% url 'removeclient' id=id %}">Delete</a>
            {% else %}
                New Client
            {% endif %}
        </h5>
        <hr/>
        <div class="card-text">
            <form action="" method="post">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-12">
                        {{ form.name|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                Address
                            </div>
                            <div class="card-body">
                                <div class="card-text">
                                    {{ form.address1|as_crispy_field }}
                                    {{ form.address2|as_crispy_field }}
                                    {{ form.city|as_crispy_field }}
                                    {{ form.postcode|as_crispy_field }}
                                    {{ form.state|as_crispy_field }}
                                    {{ form.country|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card contacts">
                            <div class="card-header">
                                Contacts
                                {% if id %}
                                    <a href="{% url 'listcontacts' clientid=id %}" id="edit_contacts" class="btn btn-info float-md-right">Edit</a>
                                {% endif %}
                            </div>
                            <div class="card-body">
                                <div class="card-text">
                                    {% if id %}
                                        {% if contacts|length > 0 %}
                                            <table class="table table-striped">
                                                <thead>
                                                    <th>Name</th>
                                                    <th>Email</th>
                                                </thead>
                                                <tbody class="contacts_list clickable"  clientid="{{ id }}">
                                                    {% for contact in contacts %}
                                                        <tr><td>{{ contact.firstname }} {{ contact.lastname }}</td>
                                                            <td>{{ contact.email }}</td></tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>

                                            <br/>
                                            <table style="width: 100%">
                                                <tr>
                                                    <td>
                                                        <h5>Notification Groups</h5>
                                                    </td>
                                                    <td>
                                                        <div class="float-md-right">
                                                            <div class="input-group mb-3">
                                                              <input id="ng_name" type="text" class="form-control" value="{{ form.name.value }}">
                                                              <div class="input-group-append">
                                                                <button id="add_ng" class="btn btn-success" clientid="{{ id }}" type="button">Add</button>
                                                              </div>
                                                            </div>

                                                        </div>
                                                    </td>
                                                </tr>
                                            </table>
                                            <br/>
                                            <table class="table table-striped" id="nglist">
                                                <thead>
                                                    <th>Name</th>
                                                    <th>Email List</th>
                                                    <th></th>
                                                </thead>
                                                <tbody class="ng_list clickable">
                                                    {% for ng in notificationgroups %}
                                                        <tr><td>{{ ng.name }}</td>
                                                            <td>{% for c in ng.contacts.all %}
                                                                {{ c.email }}<br/>
                                                                {%  endfor %}
                                                            </td>
                                                        <td>
                                                            <div class="float-right">
                                                                <a href="{% url 'listcontactsselection' refid=ng.id clientid=id %}" id="edit_ng" class="btn btn-info">Edit</a>
                                                                <button ngid="{{ ng.id }}" class="btn btn-danger delete_ng">X</button>
                                                            </div>

                                                        </td></tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        {% else %}
                                            No contacts.
                                        {%  endif %}
                                    {%  else %}
                                        Save client before adding contacts.
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-right">
                        <a href="{% url 'listclients' %}" class="btn btn-danger">Cancel</a>
                        <input type="submit" class="btn btn-success" value="Save">
                    </div>
                </div>

            </form>
        </div>

      </div>
    </div>


{% endblock %}

templates/forms/contactform.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="card page-card">
      <div class="card-body">
        <h5 class="card-title">
            <a class="btn btn-info" href="{% url 'listcontacts' clientid=clientid %}">Back</a>
            {% if id %}
                Contact #{{ id }}
                <a class="btn btn-danger float-md-right" href="{% url 'removecontact' clientid=clientid id=id %}">Delete</a>
            {% else %}
                New Contact
            {% endif %}
        </h5>
        <hr>
        <div class="card-text">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.client }}
                <div class="row">
                    <div class="col-md-6">
                        {{ form.firstname|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.lastname|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.phone|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-right">
                        <input type="submit" class="btn btn-success" value="Save">
                    </div>
                </div>

            </form>
        </div>

      </div>
</div>

{% endblock %}

templates/forms/jobform.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="card page-card">
      <div class="card-body">
        <h5 class="card-title">
            <a class="btn btn-info" href="{% url 'listjobs' %}">Back</a>
            {% if id %}
                Job #{{ id }}
                <a class="btn btn-danger float-md-right" href="{% url 'removejob' id=id %}">Delete</a>
            {% else %}
                New Job
            {% endif %}
        </h5>
        <hr>
        <div class="card-text">
            <form action="" method="post">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-6">
                        {{ form.client|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.ponumber|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.notificationgroup|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-right">
                        <input type="submit" class="btn btn-success" value="Save">
                    </div>
                </div>
                {% if id %}
                    <hr>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card-title">
                                        <h5>Samples
                                            <div class=" float-md-right">
                                                <a class="btn btn-success" href="{%  url 'listjobresults' id=id %}">Test Results</a>
                                                <a class="btn btn-info" href="{%  url 'listsamplesselection' refid=id %}">Edit Samples</a>
                                            </div>
                                        </h5>
                                        <br/>
                                    </div>

                                    <div class="card-text">
                                        <hr>
                                        <div id="jobsamples">
                                            {% include "includes/jobsample.html" %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card-title">
                                        <h5>Assign Tests
                                        <span class="btn btn-info float-md-right" id="assigntests" job_id="{{ id }}">Assign</span></h5>
                                        <br/>
                                    </div>
                                    <div class="card-text">
                                        <hr>
                                        <table>
                                            <tbody>
                                                <tr>
                                                    <td style="padding-right: 40px; padding-bottom: 40px;">
                                                        Add Test
                                                    </td>
                                                    <td style="padding-right: 40px; padding-bottom: 40px;">
                                                       <div class="dropdown">
                                                          <button id="testselect" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            Please Select
                                                          </button>
                                                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                              {% for t in tests %}
                                                                <span class="dropdown-item" value="{{ t.id }}">TM{{ t.tmnumber }} - {{t.name}}</span>
                                                              {% endfor %}
                                                          </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="padding-right: 40px; padding-bottom: 40px;">
                                                        Apply to
                                                    </td>
                                                    <td style="padding-right: 40px; padding-bottom: 40px;">
                                                        <div class="form-check-inline">
                                                          <label class="form-check-label">
                                                            <input id="applyall" type="radio" class="form-check-input" name="optradio" checked>All Samples
                                                          </label>
                                                        </div>
                                                        <div class="form-check-inline">
                                                          <label class="form-check-label">
                                                            <input type="radio" class="form-check-input" name="optradio">Selected Samples
                                                          </label>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}


            </form>
        </div>

      </div>
    </div>



    <div class="card page-card">
      <div class="card-body">
        <div class="card-text">
            <h3>Reports</h3>
            <table class="table table-striped" id="reportlist">
                <thead>
                    <th></th>
                    <th>Report Reference</th>
                    <th style="width: 50%">Report Name</th>
                    <th></th>
                </thead>
                <tbody>
                    {% for r in reports %}
                        <tr class="report" id="{{ r.id }}">
                            <td><button type="button" class="btn btn-info download_report" reportid="{{ r.id }}">Download</button>
                            <button type="button" class="btn btn-success email_report" reportid="{{ r.id }}">Email</button></td>
                            <td>#{{ r.job_id }} - {{ r.reportno }}</td>
                            <td>{{ r.name }}</td>
                            <td><button type="button" class="btn btn-danger delete_report" reportid="{{ r.id }}">Delete</button></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>



         </div>
      </div>
    </div>
{% endblock %}

templates/forms/methodform.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="card page-card">
      <div class="card-body">
        <h5 class="card-title">
            <a class="btn btn-info" href="{% url 'listmethods' %}">Back</a>
            {% if id %}
                Test Method #{{ id }}
                <a class="btn btn-danger float-md-right" href="{% url 'removemethod' id=id %}">Delete</a>
            {% else %}
                New Test Method
            {% endif %}
        </h5>
        <hr>
        <div class="card-text">
            <form action="" method="post">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-4">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.tmnumber|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.reporttype|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        {{ form.decimalplaces|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.errortype|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.error|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        {{ form.description|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-right">
                        <input type="submit" class="btn btn-success" value="Save">
                    </div>
                </div>

            </form>
        </div>

      </div>
</div>

{% endblock %}

templates/forms/sampleform.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="card page-card">
      <div class="card-body">
        <h5 class="card-title">
            <a class="btn btn-info" href="{% url 'listsamples' %}">Back</a>
            {% if id %}
                Sample #{{ id }}
                <a class="btn btn-danger float-md-right" href="{% url 'removesample' id=id %}">Delete</a>
            {% else %}
                New Sample
            {% endif %}
        </h5>
        <hr>
        <div class="card-text">
            <form action="" method="post">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-4">
                        {{ sampleform.name|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ sampleform.clientref|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ sampleform.batch|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        {{ sampleform.condition|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ sampleform.description|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ sampleform.received|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        {{ sampleform.storage|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ sampleform.client|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ sampleform.notificationgroup|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {% if id %}
                            <a class="btn btn-info" href="{% url 'copysampleform' sampleid=id %}">Copy</a>
                        {% endif %}
                    </div>
                    <div class="col-md-6 text-right">
                        <input type="submit" class="btn btn-success" value="Save">
                    </div>
                </div>

            </form>
        </div>

      </div>
</div>

    <script>
      $(function () {
        $("#id_received").datepicker({
            "dateFormat": 'dd/mm/yy'
        });
      });
    </script>
{% endblock %}

templates/forms/templateform.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="card page-card">
      <div class="card-body">
        <h5 class="card-title">
            <a class="btn btn-info" href="{% url 'listtemplates' %}">Back</a>
            {% if id %}
                Report Template #{{ id }}
                <a class="btn btn-danger float-md-right" href="{% url 'removetemplate' id=id %}">Delete</a>
            {% else %}
                New Report Template
            {% endif %}
        </h5>
        <hr>
        <div class="card-text">
            <form action="" method="post"  enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-4">
                        {{ form.name|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        {{ form.report_type|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        {{ form.document }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">

                    </div>
                    <div class="col-md-6 text-right">
                        <input type="submit" class="btn btn-success" value="Save">
                    </div>
                </div>

            </form>
        </div>

      </div>
</div>

{% endblock %}